services:
  churn-app:
    build:
      context: .  # Agora o contexto é a raiz real do projeto
      dockerfile: docker/Dockerfile
    container_name: churn_radar_prod
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - ENV=production
      - PYTHONPATH=/app
      - CONFIG_PATH=/app/configs # Força o caminho que o loader procura
    restart: unless-stopped

  mlflow-server:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: churn_mlflow
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///mlflow.db